-- Seed file generated by seed.ts

-- Brands
INSERT INTO brands (id, name, slug) VALUES ('46820b84-c571-4baa-b574-76f439d67c70', 'Chevrolet', 'chevrolet');
INSERT INTO brands (id, name, slug) VALUES ('ea03fba3-0dcd-465e-be75-aa1337c15ab7', 'Fiat', 'fiat');
INSERT INTO brands (id, name, slug) VALUES ('d2fd91b7-8e9c-45ac-b226-9ebe9a3d12b3', 'Volkswagen', 'vw');
INSERT INTO brands (id, name, slug) VALUES ('8fcad585-3ee3-4e03-bde0-3668d844c1a4', 'Ford', 'ford');
INSERT INTO brands (id, name, slug) VALUES ('bca329bf-3a5e-4ce3-bc45-cbd001149bf4', 'Toyota', 'toyota');

-- Models
INSERT INTO car_models (id, brand_id, name, slug) VALUES ('79cf06af-ac9c-4c8f-ade2-fc6e280087c8', '46820b84-c571-4baa-b574-76f439d67c70', 'Onix', 'onix');
INSERT INTO car_models (id, brand_id, name, slug) VALUES ('23d79710-cfa0-41eb-97fe-82d70bf1a117', 'ea03fba3-0dcd-465e-be75-aa1337c15ab7', 'Strada', 'strada');
INSERT INTO car_models (id, brand_id, name, slug) VALUES ('97bc45f7-0685-4d4c-bb02-eb89b7cc49b0', 'd2fd91b7-8e9c-45ac-b226-9ebe9a3d12b3', 'Polo', 'polo');

-- Car Versions
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('9f265656-28da-487c-9374-16d7dbd8be70', '79cf06af-ac9c-4c8f-ade2-fc6e280087c8', 2020, 'LTZ', '1.0 Turbo');
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('f5185185-0625-4ebc-a2d9-4d09fd888ea9', '79cf06af-ac9c-4c8f-ade2-fc6e280087c8', 2018, 'LT', '1.0 8v Flex');
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('f2d5543d-1d31-4b63-b14b-4ebf98d74a00', '23d79710-cfa0-41eb-97fe-82d70bf1a117', 2022, 'Endurance', '1.4 Fire');
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('ef922d05-bc3b-4e1e-96a2-19c0a3576de1', '97bc45f7-0685-4d4c-bb02-eb89b7cc49b0', 2021, 'Highline', '1.0 TSI');

-- Categories
INSERT INTO categories (id, name, slug) VALUES ('d91d31d9-75e6-443d-99d0-2cf6d6b1f57d', 'Filtros', 'filtros');
INSERT INTO categories (id, name, slug) VALUES ('618dc32c-e3c5-4ba7-bef8-7150dc80270f', 'Freios', 'freios');
INSERT INTO categories (id, name, slug) VALUES ('59856e8a-5b01-4ea8-a4be-1a994024a19c', 'Suspensão', 'suspensao');
INSERT INTO categories (id, name, slug) VALUES ('66587748-b4db-4d23-8fd2-556af9ae2c34', 'Motor', 'motor');

-- Master Parts
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('a66be827-5840-4c56-b00f-84212bb1f063', 'Filtro de Óleo', 'Tecfil', 'PSL55', 'd91d31d9-75e6-443d-99d0-2cf6d6b1f57d', 'N/A');
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('5dcb61a4-57e6-4327-99c6-2de4ed044332', 'Filtro de Ar', 'Fram', 'CA9999', 'd91d31d9-75e6-443d-99d0-2cf6d6b1f57d', 'N/A');
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('53931577-5973-441a-b170-a08d3e9f4115', 'Pastilha de Freio', 'Bosch', '0986BB0999', '618dc32c-e3c5-4ba7-bef8-7150dc80270f', 'Dianteira');
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('4e0e464e-6403-40bc-b67a-71ef2128cdda', 'Pastilha de Freio', 'Cobreq', 'N-1234', '618dc32c-e3c5-4ba7-bef8-7150dc80270f', 'Traseira');

-- Part Compatibility
INSERT INTO part_compatibility (part_id, version_id) VALUES ('a66be827-5840-4c56-b00f-84212bb1f063', '9f265656-28da-487c-9374-16d7dbd8be70');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('a66be827-5840-4c56-b00f-84212bb1f063', 'f5185185-0625-4ebc-a2d9-4d09fd888ea9');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('a66be827-5840-4c56-b00f-84212bb1f063', 'f2d5543d-1d31-4b63-b14b-4ebf98d74a00');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('a66be827-5840-4c56-b00f-84212bb1f063', 'ef922d05-bc3b-4e1e-96a2-19c0a3576de1');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('5dcb61a4-57e6-4327-99c6-2de4ed044332', '9f265656-28da-487c-9374-16d7dbd8be70');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('5dcb61a4-57e6-4327-99c6-2de4ed044332', 'f5185185-0625-4ebc-a2d9-4d09fd888ea9');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('5dcb61a4-57e6-4327-99c6-2de4ed044332', 'f2d5543d-1d31-4b63-b14b-4ebf98d74a00');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('5dcb61a4-57e6-4327-99c6-2de4ed044332', 'ef922d05-bc3b-4e1e-96a2-19c0a3576de1');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('53931577-5973-441a-b170-a08d3e9f4115', '9f265656-28da-487c-9374-16d7dbd8be70');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('53931577-5973-441a-b170-a08d3e9f4115', 'f5185185-0625-4ebc-a2d9-4d09fd888ea9');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('53931577-5973-441a-b170-a08d3e9f4115', 'f2d5543d-1d31-4b63-b14b-4ebf98d74a00');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('53931577-5973-441a-b170-a08d3e9f4115', 'ef922d05-bc3b-4e1e-96a2-19c0a3576de1');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('4e0e464e-6403-40bc-b67a-71ef2128cdda', '9f265656-28da-487c-9374-16d7dbd8be70');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('4e0e464e-6403-40bc-b67a-71ef2128cdda', 'f5185185-0625-4ebc-a2d9-4d09fd888ea9');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('4e0e464e-6403-40bc-b67a-71ef2128cdda', 'f2d5543d-1d31-4b63-b14b-4ebf98d74a00');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('4e0e464e-6403-40bc-b67a-71ef2128cdda', 'ef922d05-bc3b-4e1e-96a2-19c0a3576de1');

-- Stores
INSERT INTO stores (id, name, address, city, state, whatsapp, rating) VALUES ('3d785617-c22a-43ff-b44e-d8ee0b78b252', 'AutoPeças Paulista', 'Av. Paulista, 1000', 'São Paulo', 'SP', '5511999999999', 4.8);
INSERT INTO stores (id, name, address, city, state, whatsapp, rating) VALUES ('9b5caaf3-77b3-4977-a66b-947c8b66b7db', 'Freio Certo BH', 'Rua das Peças, 50', 'Belo Horizonte', 'MG', '5531988888888', 4.5);
INSERT INTO stores (id, name, address, city, state, whatsapp, rating) VALUES ('7cc8958c-19a5-4fc6-9f8f-1433dcf4c911', 'Mecânica Total SP', 'Rua Augusta, 500', 'São Paulo', 'SP', '5511977777777', 4.9);

-- Store Offers
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('84d04931-8e33-4d3e-a742-3acc634f117c', '3d785617-c22a-43ff-b44e-d8ee0b78b252', 'a66be827-5840-4c56-b00f-84212bb1f063', 45, 'NOVO');
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('d9edfc4f-29a6-49a9-8b47-7189f3c28aec', '9b5caaf3-77b3-4977-a66b-947c8b66b7db', 'a66be827-5840-4c56-b00f-84212bb1f063', 50, 'NOVO');
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('86d7538d-665f-4118-9f61-631aacbc13a8', '7cc8958c-19a5-4fc6-9f8f-1433dcf4c911', '53931577-5973-441a-b170-a08d3e9f4115', 180, 'NOVO');
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('fbd27142-a5f2-453a-8c41-c5fe25175d1e', '3d785617-c22a-43ff-b44e-d8ee0b78b252', '4e0e464e-6403-40bc-b67a-71ef2128cdda', 120, 'NOVO');
