-- Seed file generated by seed.ts

-- Brands
INSERT INTO brands (id, name, slug) VALUES ('e58f3123-6174-4731-b934-c7b2ec440dcf', 'Chevrolet', 'chevrolet');
INSERT INTO brands (id, name, slug) VALUES ('e09c1656-f583-4d84-90fd-74ab435e5e28', 'Fiat', 'fiat');
INSERT INTO brands (id, name, slug) VALUES ('a3cbed71-3f8c-4da2-90f0-2d1fc2a8c8b1', 'Volkswagen', 'vw');
INSERT INTO brands (id, name, slug) VALUES ('2fd4e9bf-65b9-4bb8-aa76-2d0378288a9e', 'Ford', 'ford');
INSERT INTO brands (id, name, slug) VALUES ('2e04fb40-5f6a-46c0-b99c-e5033f873a8c', 'Toyota', 'toyota');

-- Models
INSERT INTO car_models (id, brand_id, name, slug) VALUES ('eedee43b-9552-4f79-b170-b4a8aeb2d885', 'e58f3123-6174-4731-b934-c7b2ec440dcf', 'Onix', 'onix');
INSERT INTO car_models (id, brand_id, name, slug) VALUES ('e9819b9a-a71a-46fe-8e6b-ce1f0c3b46a5', 'e09c1656-f583-4d84-90fd-74ab435e5e28', 'Strada', 'strada');
INSERT INTO car_models (id, brand_id, name, slug) VALUES ('fdea2fe9-d77f-431f-a50d-85cb9da3b49f', 'a3cbed71-3f8c-4da2-90f0-2d1fc2a8c8b1', 'Polo', 'polo');

-- Car Versions
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('5acb6aa2-998b-4562-b171-20e405672889', 'eedee43b-9552-4f79-b170-b4a8aeb2d885', 2020, 'LTZ', '1.0 Turbo');
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('113719d4-dd8a-4a84-a29d-ee017f33293b', 'eedee43b-9552-4f79-b170-b4a8aeb2d885', 2018, 'LT', '1.0 8v Flex');
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('92b5c338-ab02-4b21-89cf-86b27a2a70b6', 'e9819b9a-a71a-46fe-8e6b-ce1f0c3b46a5', 2022, 'Endurance', '1.4 Fire');
INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES ('137aaf4a-73e1-4608-8f73-ccfe125fae5f', 'fdea2fe9-d77f-431f-a50d-85cb9da3b49f', 2021, 'Highline', '1.0 TSI');

-- Categories
INSERT INTO categories (id, name, slug) VALUES ('e3893129-5412-48e6-94ba-44bc3ad6aa71', 'Filtros', 'filtros');
INSERT INTO categories (id, name, slug) VALUES ('df076e6f-ec0d-4e03-8bbe-fa722d15884a', 'Freios', 'freios');
INSERT INTO categories (id, name, slug) VALUES ('f6bb6b73-6585-4c7e-b9ca-dea2b2f11573', 'Suspensão', 'suspensao');
INSERT INTO categories (id, name, slug) VALUES ('25a62261-539b-4a29-b1ac-7bf769b362ed', 'Motor', 'motor');

-- Master Parts
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('adceb4fc-2468-4fb4-bbd4-444a079bde86', 'Filtro de Óleo', 'Tecfil', 'PSL55', 'e3893129-5412-48e6-94ba-44bc3ad6aa71', 'N/A');
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('1551ac8c-80a3-4f32-abf9-d0256f5ba281', 'Filtro de Ar', 'Fram', 'CA9999', 'e3893129-5412-48e6-94ba-44bc3ad6aa71', 'N/A');
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('d516d1cd-8cba-49f2-93b0-782e57b1e1b3', 'Pastilha de Freio', 'Bosch', '0986BB0999', 'df076e6f-ec0d-4e03-8bbe-fa722d15884a', 'Dianteira');
INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES ('99fa8f22-0fab-4f04-a536-d526ca049c61', 'Pastilha de Freio', 'Cobreq', 'N-1234', 'df076e6f-ec0d-4e03-8bbe-fa722d15884a', 'Traseira');

-- Part Compatibility
INSERT INTO part_compatibility (part_id, version_id) VALUES ('adceb4fc-2468-4fb4-bbd4-444a079bde86', '5acb6aa2-998b-4562-b171-20e405672889');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('adceb4fc-2468-4fb4-bbd4-444a079bde86', '113719d4-dd8a-4a84-a29d-ee017f33293b');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('adceb4fc-2468-4fb4-bbd4-444a079bde86', '92b5c338-ab02-4b21-89cf-86b27a2a70b6');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('adceb4fc-2468-4fb4-bbd4-444a079bde86', '137aaf4a-73e1-4608-8f73-ccfe125fae5f');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('1551ac8c-80a3-4f32-abf9-d0256f5ba281', '5acb6aa2-998b-4562-b171-20e405672889');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('1551ac8c-80a3-4f32-abf9-d0256f5ba281', '113719d4-dd8a-4a84-a29d-ee017f33293b');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('1551ac8c-80a3-4f32-abf9-d0256f5ba281', '92b5c338-ab02-4b21-89cf-86b27a2a70b6');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('1551ac8c-80a3-4f32-abf9-d0256f5ba281', '137aaf4a-73e1-4608-8f73-ccfe125fae5f');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('d516d1cd-8cba-49f2-93b0-782e57b1e1b3', '5acb6aa2-998b-4562-b171-20e405672889');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('d516d1cd-8cba-49f2-93b0-782e57b1e1b3', '113719d4-dd8a-4a84-a29d-ee017f33293b');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('d516d1cd-8cba-49f2-93b0-782e57b1e1b3', '92b5c338-ab02-4b21-89cf-86b27a2a70b6');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('d516d1cd-8cba-49f2-93b0-782e57b1e1b3', '137aaf4a-73e1-4608-8f73-ccfe125fae5f');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('99fa8f22-0fab-4f04-a536-d526ca049c61', '5acb6aa2-998b-4562-b171-20e405672889');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('99fa8f22-0fab-4f04-a536-d526ca049c61', '113719d4-dd8a-4a84-a29d-ee017f33293b');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('99fa8f22-0fab-4f04-a536-d526ca049c61', '92b5c338-ab02-4b21-89cf-86b27a2a70b6');
INSERT INTO part_compatibility (part_id, version_id) VALUES ('99fa8f22-0fab-4f04-a536-d526ca049c61', '137aaf4a-73e1-4608-8f73-ccfe125fae5f');

-- Company
INSERT INTO companies (id, cnpj, name, email, password_hash, active_plan) VALUES ('0fe052b7-3cd0-4dbd-b824-d9b38bdc7282', '12345678000199', 'Lojas Fictícias Rede', 'contato@rede.com', 'dummy_hash', 'PROFISSIONAL');

-- Stores
INSERT INTO stores (id, company_id, name, address, city, state, whatsapp, rating) VALUES ('ff83b9e3-5eed-4e40-9933-4de3bd9fc9f6', '0fe052b7-3cd0-4dbd-b824-d9b38bdc7282', 'AutoPeças Paulista', 'Av. Paulista, 1000', 'São Paulo', 'SP', '5511999999999', 4.8);
INSERT INTO stores (id, company_id, name, address, city, state, whatsapp, rating) VALUES ('9d5194ab-c53e-4637-a820-b4df6fc7d7a2', '0fe052b7-3cd0-4dbd-b824-d9b38bdc7282', 'Freio Certo BH', 'Rua das Peças, 50', 'Belo Horizonte', 'MG', '5531988888888', 4.5);
INSERT INTO stores (id, company_id, name, address, city, state, whatsapp, rating) VALUES ('717310d2-841f-43c8-9384-4e27288e9d3c', '0fe052b7-3cd0-4dbd-b824-d9b38bdc7282', 'Mecânica Total SP', 'Rua Augusta, 500', 'São Paulo', 'SP', '5511977777777', 4.9);

-- Store Offers
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('84d56fa4-fac9-4300-b9c1-3c426c887cbf', 'ff83b9e3-5eed-4e40-9933-4de3bd9fc9f6', 'adceb4fc-2468-4fb4-bbd4-444a079bde86', 45, 'NOVO');
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('24898a85-ebf9-43c0-92a6-ec8dcc8a44c5', '9d5194ab-c53e-4637-a820-b4df6fc7d7a2', 'adceb4fc-2468-4fb4-bbd4-444a079bde86', 50, 'NOVO');
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('09d4dbbd-52d1-495d-b120-7874901687fb', '717310d2-841f-43c8-9384-4e27288e9d3c', 'd516d1cd-8cba-49f2-93b0-782e57b1e1b3', 180, 'NOVO');
INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES ('efd53ac7-0723-456d-ba5a-39edd616a6b8', 'ff83b9e3-5eed-4e40-9933-4de3bd9fc9f6', '99fa8f22-0fab-4f04-a536-d526ca049c61', 120, 'NOVO');
