import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

// Helpers to generate SQL
const escapeStr = (str: string) => str ? `'${str.replace(/'/g, "''")}'` : 'NULL';
const genId = () => crypto.randomUUID();

// ----------------------------------------------------
// 1. DATA TO SEED
// ----------------------------------------------------

const brands = [
  { id: genId(), name: 'Chevrolet', slug: 'chevrolet' },
  { id: genId(), name: 'Fiat', slug: 'fiat' },
  { id: genId(), name: 'Volkswagen', slug: 'vw' },
  { id: genId(), name: 'Ford', slug: 'ford' },
  { id: genId(), name: 'Toyota', slug: 'toyota' },
];

const chevroletId = brands.find(b => b.slug === 'chevrolet')!.id;
const fiatId = brands.find(b => b.slug === 'fiat')!.id;
const vwId = brands.find(b => b.slug === 'vw')!.id;

const models = [
  { id: genId(), brandId: chevroletId, name: 'Onix', slug: 'onix' },
  { id: genId(), brandId: fiatId, name: 'Strada', slug: 'strada' },
  { id: genId(), brandId: vwId, name: 'Polo', slug: 'polo' },
];

const onixId = models.find(m => m.slug === 'onix')!.id;
const stradaId = models.find(m => m.slug === 'strada')!.id;
const poloId = models.find(m => m.slug === 'polo')!.id;

const carVersions = [
  { id: genId(), modelId: onixId, year: 2020, versionName: 'LTZ', engine: '1.0 Turbo' },
  { id: genId(), modelId: onixId, year: 2018, versionName: 'LT', engine: '1.0 8v Flex' },
  { id: genId(), modelId: stradaId, year: 2022, versionName: 'Endurance', engine: '1.4 Fire' },
  { id: genId(), modelId: poloId, year: 2021, versionName: 'Highline', engine: '1.0 TSI' },
];

const categories = [
  { id: genId(), name: 'Filtros', slug: 'filtros' },
  { id: genId(), name: 'Freios', slug: 'freios' },
  { id: genId(), name: 'Suspensão', slug: 'suspensao' },
  { id: genId(), name: 'Motor', slug: 'motor' },
];

const filterId = categories.find(c => c.slug === 'filtros')!.id;
const brakeId = categories.find(c => c.slug === 'freios')!.id;

const masterParts = [
  { id: genId(), name: 'Filtro de Óleo', manufacturer: 'Tecfil', manufacturerCode: 'PSL55', categoryId: filterId, position: 'N/A' },
  { id: genId(), name: 'Filtro de Ar', manufacturer: 'Fram', manufacturerCode: 'CA9999', categoryId: filterId, position: 'N/A' },
  { id: genId(), name: 'Pastilha de Freio', manufacturer: 'Bosch', manufacturerCode: '0986BB0999', categoryId: brakeId, position: 'Dianteira' },
  { id: genId(), name: 'Pastilha de Freio', manufacturer: 'Cobreq', manufacturerCode: 'N-1234', categoryId: brakeId, position: 'Traseira' },
];

// Link every part to all versions for testing purposes
const partCompatibilities: { partId: string, versionId: string }[] = [];
for (const part of masterParts) {
  for (const version of carVersions) {
    partCompatibilities.push({ partId: part.id, versionId: version.id });
  }
}

const stores = [
  { id: genId(), name: 'AutoPeças Paulista', address: 'Av. Paulista, 1000', city: 'São Paulo', state: 'SP', whatsapp: '5511999999999', rating: 4.8 },
  { id: genId(), name: 'Freio Certo BH', address: 'Rua das Peças, 50', city: 'Belo Horizonte', state: 'MG', whatsapp: '5531988888888', rating: 4.5 },
  { id: genId(), name: 'Mecânica Total SP', address: 'Rua Augusta, 500', city: 'São Paulo', state: 'SP', whatsapp: '5511977777777', rating: 4.9 },
];

const offers = [
  { id: genId(), storeId: stores[0].id, partId: masterParts[0].id, price: 45.00, condition: 'NOVO' },
  { id: genId(), storeId: stores[1].id, partId: masterParts[0].id, price: 50.00, condition: 'NOVO' },
  { id: genId(), storeId: stores[2].id, partId: masterParts[2].id, price: 180.00, condition: 'NOVO' },
  { id: genId(), storeId: stores[0].id, partId: masterParts[3].id, price: 120.00, condition: 'NOVO' },
];

// ----------------------------------------------------
// 2. GENERATE SQL STATEMENTS
// ----------------------------------------------------

let sqlContent = `-- Seed file generated by seed.ts\n\n`;

// Brands
sqlContent += `-- Brands\n`;
for (const b of brands) {
  sqlContent += `INSERT INTO brands (id, name, slug) VALUES (${escapeStr(b.id)}, ${escapeStr(b.name)}, ${escapeStr(b.slug)});\n`;
}

// Models
sqlContent += `\n-- Models\n`;
for (const m of models) {
  sqlContent += `INSERT INTO car_models (id, brand_id, name, slug) VALUES (${escapeStr(m.id)}, ${escapeStr(m.brandId)}, ${escapeStr(m.name)}, ${escapeStr(m.slug)});\n`;
}

// Versions
sqlContent += `\n-- Car Versions\n`;
for (const v of carVersions) {
  sqlContent += `INSERT INTO car_versions (id, model_id, year, version_name, engine) VALUES (${escapeStr(v.id)}, ${escapeStr(v.modelId)}, ${v.year}, ${escapeStr(v.versionName)}, ${escapeStr(v.engine)});\n`;
}

// Categories
sqlContent += `\n-- Categories\n`;
for (const c of categories) {
  sqlContent += `INSERT INTO categories (id, name, slug) VALUES (${escapeStr(c.id)}, ${escapeStr(c.name)}, ${escapeStr(c.slug)});\n`;
}

// Master Parts
sqlContent += `\n-- Master Parts\n`;
for (const p of masterParts) {
  sqlContent += `INSERT INTO master_parts (id, name, manufacturer, manufacturer_code, category_id, position) VALUES (${escapeStr(p.id)}, ${escapeStr(p.name)}, ${escapeStr(p.manufacturer)}, ${escapeStr(p.manufacturerCode)}, ${escapeStr(p.categoryId)}, ${escapeStr(p.position)});\n`;
}

// Compatibilities
sqlContent += `\n-- Part Compatibility\n`;
for (const c of partCompatibilities) {
  sqlContent += `INSERT INTO part_compatibility (part_id, version_id) VALUES (${escapeStr(c.partId)}, ${escapeStr(c.versionId)});\n`;
}

// Company
const companyId = crypto.randomUUID();
sqlContent += `\n-- Company\n`;
sqlContent += `INSERT INTO companies (id, cnpj, name, email, password_hash, active_plan) VALUES ('${companyId}', '12345678000199', 'Lojas Fictícias Rede', 'contato@rede.com', 'dummy_hash', 'PROFISSIONAL');\n`;

// Stores
sqlContent += `\n-- Stores\n`;
for (const s of stores) {
  sqlContent += `INSERT INTO stores (id, company_id, name, address, city, state, whatsapp, rating) VALUES (${escapeStr(s.id)}, '${companyId}', ${escapeStr(s.name)}, ${escapeStr(s.address)}, ${escapeStr(s.city)}, ${escapeStr(s.state)}, ${escapeStr(s.whatsapp)}, ${s.rating});\n`;
}

// Offers
sqlContent += `\n-- Store Offers\n`;
for (const o of offers) {
  sqlContent += `INSERT INTO store_offers (id, store_id, part_id, price, condition) VALUES (${escapeStr(o.id)}, ${escapeStr(o.storeId)}, ${escapeStr(o.partId)}, ${o.price}, ${escapeStr(o.condition)});\n`;
}

const outputPath = path.resolve(process.cwd(), 'drizzle/seed.sql');
fs.writeFileSync(outputPath, sqlContent, 'utf-8');
console.log(`✅ Seed SQL generated at ${outputPath}`);
